### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by Iamlaoli** [bubbliiiing/yolov4-keras#98]
请问这种报错该怎么办呢
Traceback (most recent call last):
  File "D:\model\yolov4-keras\train.py", line 422, in <module>
    callbacks           = callbacks
  File "D:\anaconda3\envs\yolov4-keras-train\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "D:\anaconda3\envs\yolov4-keras-train\lib\site-packages\keras\engine\training.py", line 2224, in fit_generator
    class_weight=class_weight)
  File "D:\anaconda3\envs\yolov4-keras-train\lib\site-packages\keras\engine\training.py", line 1883, in train_on_batch
    outputs = self.train_function(ins)
  File "D:\anaconda3\envs\yolov4-keras-train\lib\site-packages\keras\backend\tensorflow_backend.py", line 2478, in __call__
    **self.session_kwargs)
  File "D:\anaconda3\envs\yolov4-keras-train\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "D:\anaconda3\envs\yolov4-keras-train\lib\site-packages\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\anaconda3\envs\yolov4-keras-train\lib\site-packages\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "D:\anaconda3\envs\yolov4-keras-train\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node conv2d_1/convolution (defined at anaconda3\envs\yolov4-keras-train\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
	 [[loss/add_109/_4489]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node conv2d_1/convolution (defined at anaconda3\envs\yolov4-keras-train\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'conv2d_1/convolution':
  File "model\yolov4-keras\train.py", line 276, in <module>
    model_body  = yolo_body((None, None, 3), anchors_mask, num_classes)
  File "model\yolov4-keras\nets\yolo.py", line 48, in yolo_body
    feat1,feat2,feat3 = darknet_body(inputs)
  File "model\yolov4-keras\nets\CSPdarknet53.py", line 94, in darknet_body
    x = DarknetConv2D_BN_Mish(32, (3,3))(x)
  File "model\yolov4-keras\utils\utils.py", line 11, in <lambda>
    return reduce(lambda f, g: lambda *a, **kw: g(f(*a, **kw)), funcs)
  File "model\yolov4-keras\utils\utils.py", line 11, in <lambda>
    return reduce(lambda f, g: lambda *a, **kw: g(f(*a, **kw)), funcs)
  File "anaconda3\envs\yolov4-keras-train\lib\site-packages\keras\engine\topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "anaconda3\envs\yolov4-keras-train\lib\site-packages\keras\layers\convolutional.py", line 168, in call
    dilation_rate=self.dilation_rate)
  File "anaconda3\envs\yolov4-keras-train\lib\site-packages\keras\backend\tensorflow_backend.py", line 3335, in conv2d
    data_format=tf_data_format)
  File "anaconda3\envs\yolov4-keras-train\lib\site-packages\tensorflow_core\python\ops\nn_ops.py", line 898, in convolution
    name=name)
  File "anaconda3\envs\yolov4-keras-train\lib\site-packages\tensorflow_core\python\ops\nn_ops.py", line 1009, in convolution_internal
    name=name)
  File "anaconda3\envs\yolov4-keras-train\lib\site-packages\tensorflow_core\python\ops\gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "anaconda3\envs\yolov4-keras-train\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "anaconda3\envs\yolov4-keras-train\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "anaconda3\envs\yolov4-keras-train\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "anaconda3\envs\yolov4-keras-train\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "anaconda3\envs\yolov4-keras-train\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by bubbliiiing** [comment]
什么版本
